###
GET http://localhost:8080/api/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjM1ODQ1MDMzfQ.N4ya_ZVOeY4cJ033baimclBXDX97BmjXYmpn_CJ70WM
###
POST http://localhost:8080/api/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjM1ODQ1MDMzfQ.N4ya_ZVOeY4cJ033baimclBXDX97BmjXYmpn_CJ70WM

{
    "name":"test",
    "password":"test"
}
