module.exports = [
    {
        "customerName": "Test Customer 1",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 2",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 3",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 4",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 5",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 6",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 7",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 8",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 9",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 10",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 11",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 12",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 13",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 14",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 15",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 16",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 17",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 18",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 19",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    },
    {
        "customerName": "Test Customer 20",
        "model": "alkjsd",
        "issues": "sdfjkl",
        "brand": "ksldjfkls",
        "status": false,
        "amount": 1234234,
        "detailedDescription": "sdfsdf",
    }
]